apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/production-aws-kubernetes-platform.git
    targetRevision: main
    path: helm/production-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
